---
title: "Draft_Graphs"
output: html_document
date: "2026-04-16"
editor_options: 
  chunk_output_type: console
---
```{r}
#|include: FALSE
library(ggiraph)
library(tidyverse)
library(nycflights13)
library(patchwork)
library(htmltools)
library(sf)
library(maps)
flights <- nycflights13::flights 
airports <- nycflights13::airports
flights_jan1 <- flights |>
  filter(origin == "EWR" & month == 1 & day == 1 & hour == 13) |>
  mutate(title = str_glue("EWR to {dest}, ",
                         "flight num {flight}"))
airport_names <- airports |>
  select(faa, name, lat, lon) |>
  mutate(dest = faa)
flights_jan1 |>
  left_join(airport_names)
```

```{r}
p3 <- ggplot() +
  geom_sf(data = flights_jan1, fill = "lightgrey", color = "lightgrey") +
  geom_sf_interactive(
    data = flights_jan1,
    aes(fill = title, tooltip = title, data_id = title)
  ) +
  coord_sf(crs = st_crs(3857)) +
  theme_void() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
  )
```

```{r}
us_states <- map_data("state")

us_states |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(fill = "white", color = "black") +
  geom_polygon(aes(fill = flight), color = "black")

?map
```


```{r}
scatter <- ggplot(
  data = flights_jan1,
  mapping = aes(
    x = dep_delay, y = arr_delay,
    tooltip = name, data_id = name
  )
) +
  geom_point_interactive(
    size = 3, hover_nearest = TRUE
  ) +
  labs(
    title = "Departure and Arrival Delays",
    x = "Departure Delay (minutes)", y = "Arrival Delay (minutes)"
  ) +
  theme_bw()

bar <- ggplot(
  data = flights_jan1,
  mapping = aes(
    x = reorder(flight, distance), y = distance,
    tooltip = paste(flight, "<br>Dist", distance, "mi"),
    data_id = name
  )
) +
  geom_col_interactive(fill = "skyblue") +
  coord_flip() +
  labs(
    title = "Flight Distance",
    x = "Flight Number", y = "Flight Distance in Miles"
  ) +
  theme_bw()

combined_plot <- scatter + bar +
  plot_layout(ncol = 2)

interactive_plot <- girafe(ggobj = combined_plot)
```

```{r}
flights_jan1 <- flights |>
  filter(origin == "EWR" & month == 1 & day == 1 & hour == 13) |>
  mutate(name = str_glue("EWR to {dest}, ",
                         "flight num {flight}"))

#busiest hour of the day
```

```{r}
more_dinos <- tribble(
  ~dino_answer, ~uscitizen, 	~likes_or_loves, ~neither_likes_nor_dislikes,
"Tyrannosaurus Rex",	23.686,	28.634,	18.638,
"Brontosaurus",	6.612,	9.659,	4.329,
"Triceratops",	6.457,	10.828,	2.74,
"Pterodactyl", 5.097,	7.16,	3.569,
"Velociraptor",	4.821,	7.756,	2.402,
"Stegosaurus",	3.709,	4.53,	3.386,
"Brachiosaurus",	1.721,	2.864,	0.814,
"Other",	6.31,	8.479,	4.775,
"I don't have a favorite",	39.112,	18.746,	56.062
)
more_dinos$dino_answer <- fct_inorder(rev(more_dinos$dino_answer))
```

```{r}
p1 <- ggplot(
  data = more_dinos,
  mapping = aes(x = likes_or_loves, y = dino_answer, tooltip = likes_or_loves, data_id = dino_answer)
) +
  geom_col_interactive(
    onclick = paste0(
      "this.style.fill = this.style.fill === \"red\" ? this.getAttribute(\"original-fill\") : \"red\";",
      "this.classList.toggle(\"highlighted\");",
      "var tooltip = document.getElementById(\"custom-tooltip\");",
      "tooltip.innerHTML = \"A chart by: \" + this.getAttribute(\"data-blah\");",
      "tooltip.style.display = \"block\";",
      "tooltip.style.left = (event.pageX + 10) + \"px\";",
      "tooltip.style.top = (event.pageY + 10) + \"px\";",
      "setTimeout(function() { tooltip.style.display = \"none\"; }, 1500);",
      "confetti({
        particleCount: 1000,
        spread: 70,
        origin: { y: 0.6 }
      });"
    )
  ) +
  labs(x = "Likes or Loves") +
  theme(
    axis.title.y = element_blank(),
  )


p2 <- ggplot(
  data = more_dinos,
  mapping = aes(x = neither_likes_nor_dislikes, y = dino_answer, tooltip = neither_likes_nor_dislikes, data_id = dino_answer)
) +
  geom_col_interactive(
    onclick = paste0(
      "this.style.fill = this.style.fill === \"red\" ? this.getAttribute(\"original-fill\") : \"red\";",
      "this.classList.toggle(\"highlighted\");",
      "var tooltip = document.getElementById(\"custom-tooltip\");",
      "tooltip.innerHTML = \"A chart by: \" + this.getAttribute(\"data-blah\");",
      "tooltip.style.display = \"block\";",
      "tooltip.style.left = (event.pageX + 10) + \"px\";",
      "tooltip.style.top = (event.pageY + 10) + \"px\";",
      "setTimeout(function() { tooltip.style.display = \"none\"; }, 1500);",
      "confetti({
        particleCount: 1000,
        spread: 70,
        origin: { y: 0.6 }
      });"
    )
  ) +
  labs(x = "Neither Likes Nor Dislikes") +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )

p3 <- ggplot(
  data = more_dinos,
  mapping = aes(x = uscitizen, y = dino_answer, tooltip = uscitizen, data_id = dino_answer)
) +
  geom_col_interactive(
    onclick = paste0(
      "this.style.fill = this.style.fill === \"red\" ? this.getAttribute(\"original-fill\") : \"red\";",
      "this.classList.toggle(\"highlighted\");",
      "var tooltip = document.getElementById(\"custom-tooltip\");",
      "tooltip.innerHTML = \"A chart by: \" + this.getAttribute(\"data-blah\");",
      "tooltip.style.display = \"block\";",
      "tooltip.style.left = (event.pageX + 10) + \"px\";",
      "tooltip.style.top = (event.pageY + 10) + \"px\";",
      "setTimeout(function() { tooltip.style.display = \"none\"; }, 1500);",
      "confetti({
        particleCount: 1000,
        spread: 70,
        origin: { y: 0.6 }
      });"
    )
  ) +
  labs(x = "US Adult Citizen") +
theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )


combined_plot <- p1 + p2 + p3 +
  plot_layout(ncol = 3)

interactive_plot <- girafe(ggobj = combined_plot)
interactive_plot
```

```{r}
dinos <- tribble(
  ~type, ~year, ~perc, ~unique,
  "love", 2024, 13, "love 2024",
  "like", 2024, 31, "like 2024",
  "neither", 2024, 47, "neither 2024",
  "dislike", 2024, 2, "dislike 2024",
  "hate", 2024, 3, "hate 2024",
  "don't know", 2024, 4, "don't know 2024",
  "love", 2026, 17, "love 2026",
  "like", 2026, 30, "like 2026",
  "neither", 2026, 47, "neither 2026",
  "dislike", 2026, 2, "dislike 2026",
  "hate", 2026, 1, "hate 2026",
  "don't know", 2026, 3, "don't know 2026"
)
dinos$type <- fct_inorder(dinos$type)
```

```{r}
dinoplot <- dinos |>
  ggplot() +
  geom_point_interactive(aes(x = type,
             y = perc,
             color = as.factor(year),
             tooltip = unique,
             data_id = unique),
    size = 3, position = "jitter", hover_nearest = TRUE) +
  labs(title = "How much do you like dinosuars?",
       caption = "Data from YouGov's polls, Dinosaurs
       https://yougov.com/en-us/topics/topic/Dinosaurs",
       color = "Year",
       x = "How much do you Like or Dislike dinosaurs?",
       y = "Percentage of Answers")
girafe(ggobj = dinoplot)
```


```{r}

library(ggplot2)
library(ggiraph)

# Sample plot with onclick event
p <- ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point_interactive(
    aes(onclick = "confetti({ particleCount: 150, spread: 70, origin: { y: 0.6 } });"),
    size = 3
  )

# Render the interactive plot
plot <- girafe(ggobj = p)
plot
```